// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SA.Backend.DB;
using System;

namespace SA.Backend.Migrations
{
    [DbContext(typeof(SAContext))]
    [Migration("20171120004507_AddTweet")]
    partial class AddTweet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SA.Contracts.Facebook.FacebookUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("FacebookUser");
                });

            modelBuilder.Entity("SA.Contracts.Instagram.User.instagram_media_recent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("instagram_media_recent");
                });

            modelBuilder.Entity("SA.Contracts.Twitter.SearchedTwitterUserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("twitter_searched_user_data");
                });
#pragma warning restore 612, 618
        }
    }
}
